#!/bin/bash
echo "$@"
input=$@


SUBSTRING='/access/'
if [[ "$input" == *"$SUBSTRING"* ]]; then
  echo "/access/ is part of the url, downloading directly without extracting id"
wget $input -O /tmp/veo_get.out
else


id=`echo $input | rev | cut -d / -f 1 | rev | cut -d '?' -f 1 `
#wget "$@" -O /tmp/veo_get.out


echo id=$id


#wget "https://voe.sx/e/$id" -O /tmp/veo_get.out
wget $input -O /tmp/veo_get.out

fi

#i@id=`echo "$@" | cut -d "/" -f 5`
#echo id=$id
title=`cat /tmp/veo_get.out| grep "<title>" |cut -d '>' -f 2 | cut -f 1 -d '<' | cut -d ' ' -f 2-`
title2=$title
secoundString=""
firstString=' - VOE | Content Delivery Network (CDN) & Video Cloud'
title=${title2//$firstString/$second}
#title=$title2
echo title=$title
#m3u=`cat /tmp/veo_get.out| grep m3u8 | cut -d '"' -f 4`
#mp4=`grep "'mp4': 'https:" /tmp/veo_get.out | head -n 1 | cut -d "'" -f 4`
#echo mp4=$mp4
hls=`cat /tmp/veo_get.out  | grep "'hls'" | cut -d "'" -f 4 | base64 -d`
echo hls=$hls
#hackforlazy
mp4=$hls

#ytdl_voe -o "$title"-$id.mp4 $mp4

if grep 'track kind="subtitles" label="' /tmp/veo_get.out; then 
echo subs=true;

#for i in `grep 'track kind="captions" label="' /tmp/veo_get.out`
#do 
#	echo $i
#	lang=$(echo $i | cut -d '"' -f 5)
 #       echo lang=$lang
	suburl=https://voe.sx/$( grep 'track kind="subtitles" label="' /tmp/veo_get.out | cut -d '"' -f 8|head -n 1)	
lang=$(grep 'track kind="subtitles" label="' /tmp/veo_get.out | cut -d '"' -f 6| head -n 1)
echo suburl=$suburl
echo lang=$lang

wget "$suburl" -O "$title"-$id.$lang.vtt

#lang='en'

#wget "$suburl" -O "$title"-$id.$lang.vtt
#lang='de'
#
#wget "$suburl" -O "$title"-$id.$lang.vtt

#done
fi

#ytdl_voe -o "$title"-$id.mp4 $mp4
echo ~/bin/ytdl_voe -o "$title"-$id.mp4 $mp4 --exec '~/bin/faststart.sh {}'
~/bin/ytdl_voe -o "$title"-$id.mp4 $mp4 --exec '~/bin/faststart.sh {}'


sleep 3
